apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: "nodes"
      static_configs:
        - targets:
            - "pollux.lan:9100"
          labels:
            node_name: "Pollux"
        - targets:
            - "openwrt.lan:9100"
          labels:
            node_name: "Router"
        - targets:
            - "soteria.lan:9100"
          labels:
            node_name: "Soteria"
